language: ruby
dist: trusty
rvm:
 - 2.1
install: git clone https://github.com/${TRAVIS_REPO_SLUG%%/*}/qubesos.github.io ~/qubesos.github.io
script: ~/qubesos.github.io/_utils/travis.sh
notifications:
  email:
    recipients:
      - adw@qubes-os.org
    on_success: never
    on_failure: always
