# Site settings
title: Qubes OS Project
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Qubes is a security-oriented, open-source operating system for personal
  computers.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "https://www.qubes-os.org" # the base hostname & protocol for your site
twitter_username: QubesOS
github_username:  QubesOS
# Project Settings
project_url: "https://www.qubes-os.org"
project_repo_path: "https://github.com/QubesOS"
project_repo_site: "/qubesos.github.io"
project_repo_wiki: "/qubes-wiki"
project_repo_artwork: "/qubes-artwork"

# Tor Mirror
project_url_tor: "http://qubesosmamapaxpa.onion"

# Build settings
markdown: kramdown
highlighter: pygments
timezone: UTC
encoding: utf-8
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

gems:
  - jekyll-redirect-from

collections:
  doc:
    output: true
    permalink: /doc/:path/
  hcl:
    output: false

allowed_categories:
  - press
  - announcements
  - releases
  - articles

default_author: "Qubes OS"
default_category: "announcements"
